name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install
        run: sudo apt-get install -y sshpass

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} <<EOF
            cd ./bots/CrmiusTelegram
            git reset --hard
            git pull origin main
            cd ..
            docker compose down --volumes crmiustelegram
            docker compose up -d --build crmiustelegram
          EOF
