name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CONFIGURATION
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: DEPLOY
        run: |
          ssh root@${{ secrets.SSH_HOST }} <<EOF
            cd ./CrmiusTelegram
            git pull origin main
            cd ..
            docker compose up -d --build crmiustelegram
          EOF
